In [1]:
import numpy as np
import pandas as pd

In [2]:
vet1 = np.array([1, 2, 3,4,5,6,7,8,9,10,12,22,33,81,5,9,73,456,10,69,33])
vet1 

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  12,  22,  33,
        81,   5,   9,  73, 456,  10,  69,  33])

In [3]:
type(vet1)

numpy.ndarray

In [4]:
vet2 = np.array([1,2,3,4,5])
vet2.cumsum()

array([ 1,  3,  6, 10, 15], dtype=int32)

In [5]:
print(vet1 [4])

5


In [6]:
vet1 [0] = -1
vet1

array([ -1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  12,  22,  33,
        81,   5,   9,  73, 456,  10,  69,  33])

In [7]:
vet1= np.append(vet1,9)
vet1

array([ -1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  12,  22,  33,
        81,   5,   9,  73, 456,  10,  69,  33,   9])

In [8]:
vet1 = vet1[:-1]
vet1

array([ -1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  12,  22,  33,
        81,   5,   9,  73, 456,  10,  69,  33])

In [9]:
vet1 = np.delete(vet1, -3)
vet1

array([ -1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  12,  22,  33,
        81,   5,   9,  73, 456,  69,  33])

In [10]:
vet1.shape


(20,)

In [11]:
vet1 = np.array([[0, -5],[11, 300]])
vet1

array([[  0,  -5],
       [ 11, 300]])

In [12]:
vet1.shape

(2, 2)

In [13]:
vetor2x3 = np.array([[1,2],[3,4],[5,6]])
vetor2x3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
vetor2x3.shape

(3, 2)

In [15]:
y = np.arange(5,50,5)
y

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [16]:
vet = np.array([-1,   2,   3,   4,   10,   6,   7,   3,   9,  10,  12,  22,  33,
        81,   5,   9,  73, 6,  69,  3])

In [17]:
unicos_vet = np.unique(vet)
unicos_vet

array([-1,  2,  3,  4,  5,  6,  7,  9, 10, 12, 22, 33, 69, 73, 81])

In [18]:
idades = np.array([44,45,23,23,28,19,20,19,17,51,29,28,31,32])
mediaIA2 = round(idades.mean(),3)
mediaIA2

29.214

In [19]:
j = np.unique(idades)
j

array([17, 19, 20, 23, 28, 29, 31, 32, 44, 45, 51])